"""Dreamaze package."""

from dreamaze.dataset import (
    BorderEndpointPairRule,
    CellGraphMaze,
    DatasetConfig,
    DatasetGenerationError,
    DatasetInvariantError,
    DatasetOutputFormat,
    DatasetRejectionLimitError,
    DatasetSplit,
    DatasetSplitName,
    DatasetSplits,
    MazeCondition,
    MazeFamily,
    TrainingExample,
    TrainingExampleConfig,
    build_dataset_splits,
    build_kruskal_training_example,
    build_training_example,
    build_wilson_training_example,
)
from dreamaze.evaluation import (
    EvaluationConfig,
    EvaluationMetric,
    EvaluationResult,
    evaluate_conditional_diffusion_solver,
    load_evaluation_config,
    sample_conditional_diffusion_solution_mask,
    sample_conditional_diffusion_solution_mask_trajectory,
)
from dreamaze.training import (
    TrainingConfig,
    TrainingResult,
    load_training_config,
    train_conditional_diffusion_solver,
)
from dreamaze.validation import (
    MaskStructureDiagnostics,
    SolutionValidationResult,
    ValidationReason,
    compute_mask_structure_diagnostics,
    validate_solution_mask,
)

__all__ = [
    "BorderEndpointPairRule",
    "CellGraphMaze",
    "DatasetConfig",
    "DatasetGenerationError",
    "DatasetInvariantError",
    "DatasetOutputFormat",
    "DatasetRejectionLimitError",
    "DatasetSplit",
    "DatasetSplitName",
    "DatasetSplits",
    "EvaluationConfig",
    "EvaluationMetric",
    "EvaluationResult",
    "MaskStructureDiagnostics",
    "MazeCondition",
    "MazeFamily",
    "SolutionValidationResult",
    "TrainingExample",
    "TrainingExampleConfig",
    "TrainingConfig",
    "TrainingResult",
    "ValidationReason",
    "build_dataset_splits",
    "build_kruskal_training_example",
    "build_training_example",
    "build_wilson_training_example",
    "evaluate_conditional_diffusion_solver",
    "load_evaluation_config",
    "load_training_config",
    "sample_conditional_diffusion_solution_mask",
    "sample_conditional_diffusion_solution_mask_trajectory",
    "train_conditional_diffusion_solver",
    "validate_solution_mask",
    "compute_mask_structure_diagnostics",
]
