"""Dreamaze package."""

from dreamaze.dataset import (
    BorderEndpointPairRule,
    CellGraphMaze,
    DatasetConfig,
    DatasetGenerationError,
    DatasetInvariantError,
    DatasetOutputFormat,
    DatasetRejectionLimitError,
    DatasetSplit,
    DatasetSplitName,
    DatasetSplits,
    MazeCondition,
    MazeFamily,
    TrainingExample,
    TrainingExampleConfig,
    build_dataset_splits,
    build_kruskal_training_example,
    build_training_example,
    build_wilson_training_example,
)
from dreamaze.validation import (
    SolutionValidationResult,
    ValidationReason,
    validate_solution_mask,
)

__all__ = [
    "BorderEndpointPairRule",
    "CellGraphMaze",
    "DatasetConfig",
    "DatasetGenerationError",
    "DatasetInvariantError",
    "DatasetOutputFormat",
    "DatasetRejectionLimitError",
    "DatasetSplit",
    "DatasetSplitName",
    "DatasetSplits",
    "MazeCondition",
    "MazeFamily",
    "SolutionValidationResult",
    "TrainingExample",
    "TrainingExampleConfig",
    "ValidationReason",
    "build_dataset_splits",
    "build_kruskal_training_example",
    "build_training_example",
    "build_wilson_training_example",
    "validate_solution_mask",
]
